### PR TITLE
fix(schema): remove extra 'mn' & unify all 'nm' props

### PR DESCRIPTION
**Pull request by Aidosmf**

### CODE REVIEW

**Comment by Aidosmf** [comment]
@mbasaglia seems like PR checks have failed in the previous commit as well: https://github.com/LottieFiles/lottie-docs/runs/4459070004?check_suite_focus=true

**Comment by Aidosmf** [comment]
@mbasaglia fixing the workflow error here https://github.com/LottieFiles/lottie-docs/pull/16

**Comment by Aidosmf** [comment]
@mbasaglia fixed the workflow issue in #16, feel free to make any changes as well

**Comment by mbasaglia** [comment]
> @mbasaglia fixed the workflow issue in #16, feel free to make any changes as well

I'm still not sure having single properties in separate files is good for the schema

Like blocks in this page: https://lottiefiles.github.io/lottie-docs/breakdown/builder/
Rely on each file representing a full lottie object

And it might be easier for other generators too

**Comment by mbasaglia** [comment]
I thought about it and I'd like to keep files as a logical grouping, basically 1 file per what would be a "class" in an OO model. I think it makes the schema easier to understand for readers and more consistent for code generators. I'd rather repeat property definitions than to splinter the schema

**Pull request closed without merging**
